### ISSUE TITLE
[Bug]: Hello, I am using the project template to make init the download selefra-terraform-provider-scaffolding... Error: No available release found Line 84 of the install-scaffolds. sh file latest_response= 'curl 'https://api.github.com/repos/selefra/selefra-terraform-provider-scaffolding/releases/latest' ` address failure

### ISSUE THREAD

**Issue by Gopherlinzy** [selefra/selefra-provider-template#1]
### Contact Details

huzhoulinyoujia@gmail.com

### Version

0.0.5

### What happened?

Hello, I am using the project template to make init the download selefra-terraform-provider-scaffolding... Error: No available release found 
Line 84 of the install-scaffolds. sh file latest_response= 'curl 'https://api.github.com/repos/selefra/selefra-terraform-provider-scaffolding/releases/latest' ` address failure

### Relevant log output

```shell
➜ selefra-terraform-provider-aws (main) ✗ make init
chmod u+x ./install-scaffolding.sh
./install-scaffolding.sh
begin download selefra-terraform-provider-scaffolding...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123  100   123    0     0    230      0 --:--:-- --:--:-- --:--:--   232
No available release found

We're sorry, but it looks like something might have gone wrong during installation.
If you need help, please join us on https://www.selefra.io/community/join
make: *** [install_selefra_terraform_provider_scaffolding] Error 1
```

**Comment by Gopherlinzy** [comment]
Problem solved:
Initialization program only need https://github.com/monserrat101/selefra-terraform-provider-scaffolding packaged into executable file under the bin directory of the current project
This is done by changing the init of the makefile to the executable file under the call bin
init::
export TERRAFORM_PROVIDER_URL=${TERRAFORM_PROVIDER}
./bin/selefra-terraform-provider-scaffolding init
You can make init normally

**Comment by monserrat101** [comment]
monserrat101/selefra-terraform-provider-scaffolding It's an informal warehouse, now use selefra/selefra-terraform-provider-scaffolding

**Comment by Gopherlinzy** [comment]
Is there any difference in the execution file using this informal library

**Comment by monserrat101** [comment]
selefra/selefra-terraform-provider-scaffolding It's a warehouse that's constantly updated and maintained, but monserrat101/selefra-terraform-provider-scaffolding just fork, It has been removed to avoid confusion

**Comment by Gopherlinzy** [comment]
Ok, I see. Thank you for your help
